# Generated by Django 5.1.3 on 2024-12-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
