# Generated by Django 5.1.3 on 2024-12-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stude_status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
